#!/usr/bin/env -S deno run --allow-read --allow-write

/**
 * Generate Concept Instances Script
 * 
 * This script scans the concepts directory and generates code to:
 * 1. Import all concept classes
 * 2. Instantiate them for sync usage
 * 3. Create a concept map for the sync engine
 * 
 * Usage: deno run --allow-read --allow-write src/scripts/generate-concept-instances.ts
 */

import { walk } from "https://deno.land/std@0.208.0/fs/walk.ts";
import { basename, dirname } from "https://deno.land/std@0.208.0/path/mod.ts";

const CONCEPTS_DIR = "./src/concepts";
const OUTPUT_FILE = "./src/generated-concept-instances.ts";

interface ConceptInfo {
    className: string;
    fileName: string;
    importPath: string;
}

async function scanConcepts(): Promise<ConceptInfo[]> {
    const concepts: ConceptInfo[] = [];

    for await (const entry of walk(CONCEPTS_DIR, {
        exts: [".ts"],
        skip: [/\.test\.ts$/, /run-tests\.ts$/],
    })) {
        if (!entry.isFile) continue;

        const fileName = basename(entry.path, ".ts");
        const relativePath = entry.path.replace(/\\/g, "/");
        const importPath = relativePath.replace("./src/", "../");

        // Class name is typically same as filename (PascalCase)
        const className = fileName;

        concepts.push({
            className,
            fileName,
            importPath,
        });
    }

    return concepts.sort((a, b) => a.className.localeCompare(b.className));
}

function generateCode(concepts: ConceptInfo[]): string {
    const imports = concepts
        .map((c) => `import { ${c.className} } from "${c.importPath}";`)
        .join("\n");

    const instantiations = concepts
        .map((c) => `  const ${c.className.charAt(0).toLowerCase() + c.className.slice(1)} = new ${c.className}();`)
        .join("\n");

    const conceptMap = concepts
        .map((c) => `    "${c.className}": ${c.className.charAt(0).toLowerCase() + c.className.slice(1)},`)
        .join("\n");

    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: src/scripts/generate-concept-instances.ts
 * Generated on: ${new Date().toISOString()}
 */

${imports}

/**
 * Initialize all concept instances
 * This function creates instances of all concepts and returns them as a Map
 * for use with the sync engine.
 */
export function initializeConceptInstances(): Map<string, any> {
${instantiations}

  // Create concept map for sync engine
  const conceptMap = new Map<string, any>([
${conceptMap}
  ]);

  return conceptMap;
}

/**
 * Get a specific concept instance by name
 */
export function getConcept<T>(conceptMap: Map<string, any>, name: string): T {
  const concept = conceptMap.get(name);
  if (!concept) {
    throw new Error(\`Concept not found: \${name}\`);
  }
  return concept as T;
}

/**
 * List all available concept names
 */
export function listConceptNames(conceptMap: Map<string, any>): string[] {
  return Array.from(conceptMap.keys()).sort();
}
`;
}

async function main() {
    console.log(" Scanning concepts directory...");
    const concepts = await scanConcepts();

    console.log(`\n Found ${concepts.length} concepts:`);
    concepts.forEach((c) => console.log(`   - ${c.className}`));

    console.log("\n Generating code...");
    const code = generateCode(concepts);

    console.log(`\n Writing to ${OUTPUT_FILE}...`);
    await Deno.writeTextFile(OUTPUT_FILE, code);

    console.log("\n Generation complete!");
    console.log("\nYou can now import and use the generated code:");
    console.log("  import { initializeConceptInstances } from './generated-concept-instances.ts';");
    console.log("  const conceptMap = initializeConceptInstances();");
}

if (import.meta.main) {
    main().catch((error) => {
        console.error(" Error:", error.message);
        Deno.exit(1);
    });
}
