/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: src/scripts/generate-concept-instances.ts
 * Generated on: 2025-12-01T13:59:06.805Z
 */

import { Bidding } from "src/concepts/Bidding.ts";
import { Feed } from "src/concepts/Feed.ts";
import { ItemListing } from "src/concepts/ItemListing.ts";
import { MessagingThread } from "src/concepts/MessagingThread.ts";
import { Requesting } from "src/concepts/Requesting.ts";
import { UserAccount } from "src/concepts/UserAccount.ts";

/**
 * Initialize all concept instances
 * This function creates instances of all concepts and returns them as a Map
 * for use with the sync engine.
 */
export function initializeConceptInstances(): Map<string, any> {
  const bidding = new Bidding();
  const feed = new Feed();
  const itemListing = new ItemListing();
  const messagingThread = new MessagingThread();
  const requesting = new Requesting();
  const userAccount = new UserAccount();

  // Create concept map for sync engine
  const conceptMap = new Map<string, any>([
    "Bidding": bidding,
    "Feed": feed,
    "ItemListing": itemListing,
    "MessagingThread": messagingThread,
    "Requesting": requesting,
    "UserAccount": userAccount,
  ]);

  return conceptMap;
}

/**
 * Get a specific concept instance by name
 */
export function getConcept<T>(conceptMap: Map<string, any>, name: string): T {
  const concept = conceptMap.get(name);
  if (!concept) {
    throw new Error(`Concept not found: ${name}`);
  }
  return concept as T;
}

/**
 * List all available concept names
 */
export function listConceptNames(conceptMap: Map<string, any>): string[] {
  return Array.from(conceptMap.keys()).sort();
}
